import fs from "node:fs/promises";
import path from "node:path";
import { tokenize, loadCorpusChunks } from "./corpus-chunks.js";

const EMBEDDINGS_PATH = path.resolve(process.cwd(), "knowledge/embeddings.json");
const OPENAI_EMBED_URL = "https://api.openai.com/v1/embeddings";
const EMBED_MODEL = "text-embedding-3-small";
const CACHE_TTL_MS = 10 * 60 * 1000;

let cache = {
  loadedAt: 0,
  chunks: [],
  hasEmbeddings: false,
};

function cosineSimilarity(a, b) {
  let dot = 0, normA = 0, normB = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    normA += a[i] * a[i];
    normB += b[i] * b[i];
  }
  if (!normA || !normB) return 0;
  return dot / (Math.sqrt(normA) * Math.sqrt(normB));
}

async function embedQuery(text) {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) return null;
  try {
    const res = await fetch(OPENAI_EMBED_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({ model: EMBED_MODEL, input: text }),
    });
    if (!res.ok) return null;
    const data = await res.json();
    return data?.data?.[0]?.embedding ?? null;
  } catch {
    return null;
  }
}

async function ensureCache() {
  const now = Date.now();
  if (now - cache.loadedAt < CACHE_TTL_MS) return;

  // Try pre-built embeddings file first (generated by scripts/embed-corpus.js)
  try {
    const raw = await fs.readFile(EMBEDDINGS_PATH, "utf8");
    const chunks = JSON.parse(raw);
    cache = { loadedAt: now, chunks, hasEmbeddings: true };
    return;
  } catch {
    // Fall through to live corpus walk (BM25 only)
  }

  try {
    const chunks = await loadCorpusChunks();
    cache = { loadedAt: now, chunks, hasEmbeddings: false };
  } catch {
    cache = { loadedAt: now, chunks: [], hasEmbeddings: false };
  }
}

export async function loadKnowledgeChunks() {
  await ensureCache();
  return cache.chunks;
}

function scoreBm25(chunks, terms, query) {
  const headingCache = new Map();
  const wholeQuery = query.trim().toLowerCase();

  return chunks.map((chunk) => {
    let score = 0;

    for (const term of terms) {
      for (const t of chunk.tokens) {
        if (t === term) score += 1;
        else if (t.startsWith(term) || term.startsWith(t)) score += 0.5;
      }
    }

    if (!headingCache.has(chunk.heading)) {
      headingCache.set(chunk.heading, tokenize(chunk.heading));
    }
    for (const term of terms) {
      if (headingCache.get(chunk.heading).includes(term)) score += 3;
    }

    if (wholeQuery && chunk.text.toLowerCase().includes(wholeQuery)) score += 5;

    return { chunk, score };
  });
}

export async function searchKnowledge(query, limit = 6) {
  await ensureCache();
  const { chunks, hasEmbeddings } = cache;

  if (!query || !chunks.length) return [];

  const terms = tokenize(query);
  const bm25 = scoreBm25(chunks, terms, query);
  const bm25Positive = bm25.filter((s) => s.score > 0);

  // No embeddings available — pure BM25
  if (!hasEmbeddings) {
    return bm25Positive
      .sort((a, b) => b.score - a.score)
      .slice(0, limit)
      .map((s) => s.chunk);
  }

  // Hybrid: embed the query and combine BM25 + cosine similarity
  const queryEmbedding = await embedQuery(query);

  // Embedding call failed — fall back to BM25
  if (!queryEmbedding) {
    return bm25Positive
      .sort((a, b) => b.score - a.score)
      .slice(0, limit)
      .map((s) => s.chunk);
  }

  const maxBm25 = Math.max(...bm25.map((s) => s.score), 1);
  const bm25Map = new Map(bm25.map((s) => [s.chunk, s.score]));

  const hybrid = chunks.map((chunk) => {
    const bm25Norm = (bm25Map.get(chunk) ?? 0) / maxBm25;
    const semantic = chunk.embedding ? cosineSimilarity(queryEmbedding, chunk.embedding) : 0;
    return { chunk, score: 0.35 * bm25Norm + 0.65 * semantic };
  });

  return hybrid
    .filter((s) => s.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map((s) => s.chunk);
}
